### ISSUE TITLE
关于2021.8总结

### ISSUE THREAD

**Issue by www516717402** [Lebhoryi/AI-News-weekly#1]
在TOOD一个总结中，你特别强调模型使用**单模型单尺度**进行测试，请问这句话在论文中哪里看到的？源代码是使用了多尺度测试。

**Comment by Lebhoryi** [comment]
此仓库仅是一个新闻摘要，不是原作者，也不是原创，更没有转发，相应文章我都有注明来源。

我看到了你说的哪篇文章，建议向该公众号后台留言纠正
https://github.com/Lebhoryi/AI-News-weekly/blob/main/2021/AI%E7%AE%80%E6%8A%A520210820.md#1-511ap%E5%8D%95%E9%98%B6%E6%AE%B5%E6%A3%80%E6%B5%8B%E5%99%A8%E7%9A%84%E6%96%B0%E7%BA%AA%E5%BD%95tood%E5%8D%B3%E6%8F%92%E5%8D%B3%E7%94%A8%E7%9A%84%E6%A3%80%E6%B5%8B%E5%99%A8%E6%8D%A2%E5%A4%B4%E6%9C%AF%E6%98%BE%E8%91%97%E6%8F%90%E5%8D%87%E6%80%A7%E8%83%BD--%E6%9E%81%E5%B8%82%E5%B9%B3%E5%8F%B0
